# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

[config]
plugins_dir = "plugins/"
auto_setup = false

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"conform.nvim" = "5.6.0"
"copilot.lua" = "scm"
"flutter-tools.nvim" = "1.9.0"
"kanagawa.nvim" = "scm"
"lualine.nvim" = "scm"
"mason-lspconfig.nvim" = "1.28.0"
"mason.nvim" = "1.10.0"
"neodev.nvim" = "2.5.2"
"oil.nvim" = "2.8.0"
"rocks-config.nvim" = "1.5.0"
"rocks-git.nvim" = "1.4.0"
"rocks.nvim" = "2.26.0" # rocks.nvim can also manage itself :D
"schemastore.nvim" = "0.2.0"
"telescope-ui-select.nvim" = "scm"
"telescope.nvim" = "scm"
# cmp-buffer = "scm"
# cmp-cmdline = "scm"
# cmp-nvim-lsp = "scm"
# cmp-path = "scm"
# cmp_luasnip = "scm"
# copilot-cmp = "scm"
nvim-autopairs = "scm"
# nvim-cmp = "scm"
nvim-dap = "0.7.0"
nvim-lspconfig = "0.1.7"
nvim-navic = "scm"
nvim-ts-autotag = "scm"
nvim-web-devicons = "0.99"
nvim-ts-context-commentstring = "scm"

auto-session = "2.0.1"
"comment.nvim" = "0.8.0"
luasnip = "2.3.0"
"typescript-tools.nvim" = "scm"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"
tree-sitter-typescript = "scm"
tree-sitter-tsx = "scm"
tree-sitter-astro = "scm"
nvim-surround = "2.1.5"
tree-sitter-jsdoc = "scm"
neorg = "8.4.0"
tree-sitter-norg-meta = "0.1.0"
tree-sitter-norg = "0.2.4"

[plugins."telescope-fzf-native.nvim"]
git = "nvim-telescope/telescope-fzf-native.nvim"

[plugins.cmp-dap]
git = "rcarriga/cmp-dap"

[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.copilot-cmp]
git = "zbirenbaum/copilot-cmp"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.neogit]
git = "NeogitOrg/neogit"
branch = "nightly"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"

[plugins.nvim-treesitter-textobjects]
git = "nvim-treesitter/nvim-treesitter-textobjects"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"

# [plugins."sonarlint.nvim"]
# git = "https://gitlab.com/schrieveslaach/sonarlint.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"

[plugins.vim-illuminate]
git = "RRethy/vim-illuminate"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"

[plugins.vim-sleuth]
git = "tpope/vim-sleuth"

[plugins."indent-blankline.nvim"]
git = "lukas-reineke/indent-blankline.nvim"
rev = "3d08501caef2329aba5121b753e903904088f7e6"
