# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

[config]
plugins_dir = "plugins/"
auto_setup = false

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks-config.nvim" = "2.1.3"
"rocks.nvim" = "2.35.1"
# nvim-cmp = "scm"
"rocks-git.nvim" = "1.5.1"

[plugins."sonarlint.nvim"]
git = "https://gitlab.com/schrieveslaach/sonarlint.nvim.git"
