#!/bin/sh
echo "Running pre-commit hook"

if [[ $(git diff --name-status --cached | grep "lazy-lock.json") ]]; then
  echo "lazy-lock.json is modified, bumping NeoVim version..."
  nvim --version | head -n 1 | awk -e ' { sub(/.*-.*-/, "", $2); print $2 }' > version
fi

if [[  $(git diff --name-status | grep "version") ]]; then
  echo "version is modified, please commit again"
  exit 1
fi
